version: "3"
services:
  app:
    container_name: api
    image: gustavbadie/api.salamatful.ir:main
    network_mode: "host"
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3022:3022
    restart: always
    volumes:
      - "/var/www/salamatful.com/admin/public/audios:/home/node/public/audios"
      - "/var/www/salamatful.com/admin/public/images:/home/node/public/images"
      - "/var/www/salamatful.com/admin/public/videos:/home/node/public/videos"
