version: "1"
services:
  app:
    container_name: api
    image: api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3022:3022
    networks:
      - nesjs-network
    restart: unless-stopped
networks:
  nesjs-network: