version: "1"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
  app:
    container_name: api
    image: api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3022:3022
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    restart: unless-stopped
networks:
  nesjs-network:
