name: Salamatful-API:CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker Image
      - run: |
          docker build . --file Dockerfile --tag api
      - name: Docker Push
      - run: |
          docker push ${{secrets.DOCKER_USERNAME}}/api.salamatful.ir
      - name: Connect to the Server and Deploy the Project
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/salamatful.com/api
